### ISSUE TITLE
Question about items

### ISSUE THREAD

**Issue by Jelly9912** [Minifixio/pocketmine-1vs1-plugin#1]
When someone dies, equipment falls to the ground ? And so it lies on the ground for the next round ?
sorry for my english :smile:

**Comment by Minifixio** [comment]
No the stuff doesn't fall on the ground, no problem for this :)

**Comment by Jelly9912** [comment]
Thanks God
awesome job :laughing:

**Comment by Minifixio** [comment]
Thanks :)))))))))

**Comment by Minifixio** [comment]
Don't forget to give a comment on PocketMine for my plugin ( it's pending approval now but it will be release soon ) I'm not english xD

**Comment by Jelly9912** [comment]
I will be waiting :D
