### ISSUE TITLE
After Kill , Thos of effect came out....

### ISSUE THREAD

**Issue by EnderKenji** [Minifixio/pocketmine-1vs1-plugin#10]
![screenshot_2015-11-25-04-24-37](https://cloud.githubusercontent.com/assets/15629214/11397249/038866c6-93b3-11e5-839e-252462573f5e.jpg)
This happened... tf.. please fix..

And another thing is, after this, player unable to damage u... 

[0.13.0] Please Fix.....

**Comment by Minifixio** [comment]
OK thanks

**Comment by Minifixio** [comment]
Ho I think it's a problem from your server because it's working on mine.

**Comment by EnderKenji** [comment]
Hmm... But after I remove 1v1 ,, this never happen again... ._.

**Comment by Minifixio** [comment]
But what is the problem precisely ;-; ?

**Comment by EnderKenji** [comment]
Idk ;-;

**Comment by Minifixio** [comment]
You don't know what is your problem ? .-.

**Comment by EnderKenji** [comment]
....

**Comment by ChiefArtz** [comment]
that is playharder problem. not the 1v1

**Comment by EnderKenji** [comment]
Oh k

**Comment by Minifixio** [comment]
I do not understand anything sorry !

**Comment by ChiefArtz** [comment]
lolol

**Comment by EnderKenji** [comment]
I think its Other plug prob.

**Comment by ChiefArtz** [comment]
it is playharder .-.
