### ISSUE TITLE
no teleport

### ISSUE THREAD

**Issue by dries-c** [Minifixio/pocketmine-1vs1-plugin#19]
i use pocketmine 1.6 bleeding 55 and there is no teleport to the arena

**Comment by robske110** [comment]
For me it works with ImagicalMine (How about running the plugin from the source code here from github, works for me)

**Comment by Minifixio** [comment]
It's working for me as well. You should use ImagicalMine for now because the official PocketMine is not release.

**Comment by dries-c** [comment]
Ok but teleport dont work i use multiworld

Dries C
Op 26-dec.-2015 11:34 schreef "Minifixio" notifications@github.com:

**Comment by dries-c** [comment]
Ok i retry

Dries C
Op 26-dec.-2015 13:42 schreef "Dries Coenen" coenendries3@gmail.com:

**Comment by robske110** [comment]
Does it work now?

**Comment by dries-c** [comment]
Yes

Dries C
Op 2-jan.-2016 23:12 schreef "Tim (robske_110)" notifications@github.com:

**Comment by Minifixio** [comment]
Excellent.
