### ISSUE TITLE
Join Sign

### ISSUE THREAD

**Issue by ghost** [Minifixio/pocketmine-1vs1-plugin#20]
Can you put a Join Sign ? Instead of typing /match
By the way . your my idol ^_^

**Comment by Minifixio** [comment]
Okay, it will be a bit easy I think but, there is a lot a thing to finish before and I will just enjoy a bit my holidays and then I will work. But thanks and nice idea :)

**Comment by robske110** [comment]
Have already programmed that should i make an pull request?

**Comment by ghost** [comment]
@Minifixio :) okay enjoy your vacation

@robske110 . please ? Make a pull request . i just need that now :)

**Comment by robske110** [comment]
I am skiing currently, I will be able to make a pull request this evening (maybe, if i am not sleeping as soon as i am at home)

**Comment by robske110** [comment]
Oh, and you can test my implementation of the sign on this server:
robskebueba.no-ip.biz:3114
(Goto PvP and Klick the signs)

**Comment by ghost** [comment]
@Robske110 . Ok

**Comment by ghost** [comment]
@Robske110. Make a Pull Request please

**Comment by robske110** [comment]
Maybe I will be able to do this this evening

**Comment by robske110** [comment]
Sorry, was busy made an pull request for better kit management now
Sign is coming up but i have to clean up that code...

**Comment by astersx** [comment]
TapToDo do the magic,  (fixed). :+1:

**Comment by ghost** [comment]
Well TapToDo Helps xD

**Comment by Michael-Tanjuakio** [comment]
i tried taptodo It doesn't work :/
