### ISSUE TITLE
If a player quits while the game is running...

### ISSUE THREAD

**Issue by robske110** [Minifixio/pocketmine-1vs1-plugin#26]
...the other one will be tped to spawn. But if the other one rejoins he won't be tped there so he is stuck in the arena and has to issue /spawn...

**Comment by Minifixio** [comment]
Mmmm... I'm really sorry but I don't understand.

**Comment by robske110** [comment]
Ok here in an better english:
The Game is running. Player 1 wins the game (Player 2 is at the DEATH screen). Then the Player 1 is teleported to spawn. (Player 2 is still at the DEATH screen) Then Player 2 accidentally presses MAIN MENU instead of RESPAWN(Would bring him to spawn). After Player2 has pressed MAIN MENU (in the RESPAWN/DEATH screen) he rejoins. And then he is alive in the arena and is forced to do /spawn! He even could wait to the next game in that area!

**Comment by Minifixio** [comment]
Ok but pressing main menu is not included like disconnecting ?

**Comment by robske110** [comment]
It is disconnecting!
So you could use onLeave/Disconnect save the player in an array and onJoin check if the player is in this array and then teleport him to spawn

**Comment by ghost** [comment]
Use alwaysspawn plugin.

**Comment by robske110** [comment]
Bug fixed in the pull request #28!
Please merge it!

**Comment by robske110** [comment]
Fixed
