### ISSUE TITLE
2vs2

### ISSUE THREAD

**Issue by MHIGists** [Minifixio/pocketmine-1vs1-plugin#35]
I've started working on 2vs2 based on your plugin .If I can give it to you or something

**Comment by Minifixio** [comment]
Nice. I'm very busy now to work on 2vs2 but you can send me it.

**Comment by Minifixio** [comment]
This night was a coding night. I think you can hope see the 1st release of 2vs2 tomorrow :) !

**Comment by robske110** [comment]
@Minifixio should i pr an join sign, an random arena cooser and an bugfix for the getServer() stuff?

**Comment by Minifixio** [comment]
If you want. _Join sign_ is very fast to add but I don't know why use **"random arena chooser"** and **getServer(),** I will fix it myse

> Funny new Markdown system :)

**Comment by robske110** [comment]
Because servers with 10 arenas and with 4 Players average will never see all 10 arenas
Join sign is in fact very fast, I will use InteractEvent ;)
