### ISSUE TITLE
Taptodo compatiblity 

### ISSUE THREAD

**Issue by Michael-Tanjuakio** [Minifixio/pocketmine-1vs1-plugin#41]
When I add the command /match(/t addcommand /match, tap block) to a block I tap it and it says it is a unknown command even though I can do /match. Please fix this. :)

**Comment by uselesswaifu** [comment]
Don't put /match put /t addcommand match

**Comment by Mike4l6** [comment]
then what  do i put so i could tap a sign/block to match instead of /match?

**Comment by RocoWayne** [comment]
im using taptodo without problems
