### ISSUE TITLE
Gliches

### ISSUE THREAD

**Issue by astersx** [Minifixio/pocketmine-1vs1-plugin#7]
Hi,  please update for pocketmine 1.6,  and make a way to no lose items,  becouse all who enter lose all stuff ., And the winer die and cant press respawn :/.  I  run a survival server so is not nice to lose all stuff wen playing 1vs 1 :(.

**Comment by astersx** [comment]
Omg still no reply?????????

**Comment by robske110** [comment]
Respawn issue is related to pocketmine not to the plugin!
And the loose stuff... You must edit the source code a bit to remove the item clears and so on! I will send you the file if i find it somewhere!

**Comment by astersx** [comment]
Ok,  please do

**Comment by astersx** [comment]
Yay found it
private function giveKit(Player $player){
		// Clear inventory
		$player->getInventory()->clearAll();

**Comment by robske110** [comment]
Yes, that's one Function There are some more!
I will send you an compiled file tomorrow!

**Comment by Minifixio** [comment]
No it's on EventManager on line 42, you have to remove $event->setDrops([]).

**Comment by astersx** [comment]
I fixed it :)

**Comment by robske110** [comment]
Block the level where your worlds are in

**Comment by astersx** [comment]
Fixed , delleted ifriend and added a /tpa plugin!!!  Omg now 1vs1 work so great,  now  1vs1 work great in a survival server :).
I blocked /tpa and all commands that can set a home or just tp there.

Keep the good work ;)

**Comment by astersx** [comment]
A ideea ::: Please if you can make 1vs1 spleef. :)

**Comment by robske110** [comment]
There are plenty spleef plugins out there

**Comment by robske110** [comment]
And PLEASE CLOSE THIS ISSUE (fixed)

**Comment by astersx** [comment]
Ok :)
