### ISSUE TITLE
setHealth()

### ISSUE THREAD

**Issue by dries-c** [Minifixio/pocketmine-1vs1-plugin#9]
setHealth()
dont work in pocketmine 1.6 and1.7

**Comment by Minifixio** [comment]
What is it so ?

**Comment by dries-c** [comment]
Yes

**Comment by dries-c** [comment]
But @ImagicalCorp
Go fix it

**Comment by robske110** [comment]
They fixed it already

**Comment by robske110** [comment]
It's partly fixed, has to do with the respawn bug and this issue should be CLOSED
